### ISSUE TITLE
BoolParam cannot be copied using setattr_param_like

### ISSUE THREAD

**Issue by charlesbaynham** [OxfordIonTrapGroup/ndscan#383]
Attempting code like

```
self.setattr_param_like("sr87", self.set_sidebands_frag)
```

where `self.set_sidebands_frag.sr87` is a `BoolParam` gives an error:

```
Traceback (most recent call last):
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_impl.py", line 368, in main
    examine(ExamineDeviceMgr, ExamineDatasetMgr, obj["file"])
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/artiq/master/worker_impl.py", line 203, in examine
    cls = exp_class(  # noqa: F841 (fill argument_mgr)
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/artiq/language/environment.py", line 254, in __init__
    self.build(*args, **kwargs)
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/entry_point.py", line 536, in build
    super().build(lambda: fragment_class(self, [], *args),
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/entry_point.py", line 91, in build
    self.fragment = fragment_init()
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/entry_point.py", line 536, in <lambda>
    super().build(lambda: fragment_class(self, [], *args),
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/artiq/language/environment.py", line 254, in __init__
    self.build(*args, **kwargs)
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/fragment.py", line 79, in build
    self.build_fragment(*args, **kwargs)
  File "/tmp/nix-shell.ZlU3KR/tmph9et531b/repository/utilities/switch_isotope.py", line 21, in build_fragment
    self.setattr_param_rebind("sr87", self.set_sidebands_frag)
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/fragment.py", line 404, in setattr_param_rebind
    handle = self.setattr_param_like(name, original_owner, original_name, **kwargs)
  File "/nix/store/blg31d13kh78p7dq45yfq5ma5h418sgc-python3-3.10.12-env/lib/python3.10/site-packages/ndscan/experiment/fragment.py", line 367, in setattr_param_like
    init_params = deepcopy(template_param.init_params)
AttributeError: 'BoolParam' object has no attribute 'init_params'
```

I can make a new param and then rebind the store myself with no problem. I think this is because in https://github.com/OxfordIonTrapGroup/ndscan/blob/b20864d832a4b8163fc51a8ac3a44f747129259e/ndscan/experiment/parameters.py#L436-L441

...the `BoolParam` is not given the parent class `ParamBase`. Is there a reason I'm missing why that shouldn't be the case?

**Comment by dnadlinger** [comment]
Fixed in #386.
